added agent-history api
racker/salus-telemetry-api pull request #103
Opened 2020-09-29 13:21 UTC by shabd67

# Resolves

[SALUS-796](https://jira.rax.io/browse/SALUS-796)

# What

Added public api for Agent-History

2020-09-29 14:17 UTC, itzg requested changes

2020-09-29 14:17 UTC, itzg commented on public/src/main/java/com/rackspace/salus/telemetry/api/config/ServicesProperties.java
> +  String ambassadorServiceUrl = "http://ambassador:8081";
The`authServiceUrl` one threw off the pattern. With this it'll work as-is in deployments
```suggestion
  String ambassadorServiceUrl = "http://ambassador:8080";
```

2020-09-29 14:28 UTC, itzg approved these changes

2020-09-29 17:37 UTC, jjbuchan requested changes
With my comment in the other PR - https://github.com/racker/salus-telemetry-ambassador/pull/100#discussion_r496908648

I think we should add the extra endpoint here too.

2020-09-30 13:57 UTC, itzg approved these changes

2020-10-01 04:06 UTC, jjbuchan approved these changes

2020-10-01 08:11 UTC, merged