Changes related to renaming PolicyMonitor to MonitorTemplate
racker/salus-telemetry-api pull request #110
Opened 2020-10-29 10:50 UTC by shabd67

# Resolves

[SALUS-1035](https://jira.rax.io/browse/SALUS-1033)

# What

Changes related to renaming PolicyMonitor to MonitorTemplate

# How

By changing endpoints and methods names in admin/public apis

# Depends on

https://github.com/racker/salus-telemetry-monitor-management/pull/224

2020-10-29 21:23 UTC, itzg approved these changes
Looks good, but can't merge until https://github.com/racker/salus-telemetry-monitor-management/pull/224 is merged too.

2020-10-29 22:29 UTC, jjbuchan approved these changes

2020-11-02 15:19 UTC, jjbuchan requested changes
Your changes in https://github.com/racker/salus-policy-management/pull/48 will affect this PR as well.

`getEffectivePolicyMonitorIdsForTenant` is still used here.

2020-11-05 15:50 UTC, itzg reviewed
Changes look good, but will let @jjbuchan provide final approval.

2020-11-23 15:05 UTC, itzg approved these changes

2020-11-23 15:23 UTC, merged